"""Emit ``regstack-theme.css`` from a designer payload.

The designer owns one file. Hosts that need bespoke ``.rs-*`` rules
should put those in a separate stylesheet that loads after this one
(the bundled theming doc explains that pattern). This keeps the
designer's contract tiny: idempotent, fully overwritten on each save,
no preserve-foreign-rules logic to maintain.

Output shape::

    /* regstack-theme.css — generated by `regstack theme design`.
       Edit by re-running the designer; hand edits will be lost on
       the next save. */

    :root {
      --rs-accent: #0d9488;
      --rs-radius: 10px;
    }

    @media (prefers-color-scheme: dark) {
      :root {
        --rs-accent: #2dd4bf;
      }
    }

Variables omitted from the payload (or set to ``""`` / ``None``) are
omitted from the output so the bundled defaults still apply.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from regstack.wizard.theme_designer.validators import ALL_VARS, RADIUS_VARS

THEME_FILE = "regstack-theme.css"

_HEADER = (
    "/* regstack-theme.css — generated by `regstack theme design`.\n"
    "   Edit by re-running the designer; hand edits will be lost on\n"
    "   the next save. */\n\n"
)

# Markers we recognise when reading an existing file back into the
# designer's form. Anything outside the markers is preserved on read
# only — the writer always emits the full file fresh.
_LIGHT_BLOCK = re.compile(r":root\s*\{([^}]*)\}", re.DOTALL)
_DARK_BLOCK = re.compile(
    r"@media\s*\(\s*prefers-color-scheme\s*:\s*dark\s*\)\s*\{[^{]*?:root\s*\{([^}]*)\}",
    re.DOTALL,
)
_VAR_LINE = re.compile(r"(--rs-[\w-]+)\s*:\s*([^;]+);")


@dataclass(slots=True)
class SaveResult:
    """Returned from :func:`save_theme` so the SPA can confirm what
    landed where.
    """

    target_path: Path
    light_count: int
    dark_count: int
    bytes_written: int


def save_theme(
    target_dir: Path,
    *,
    light: dict[str, str] | None = None,
    dark: dict[str, str] | None = None,
    filename: str = THEME_FILE,
) -> SaveResult:
    """Write a theme.css containing the supplied variable values.

    Args:
        target_dir: Directory to write into. Created if missing.
        light: Variables for the default ``:root`` block. Keys must be
            members of :data:`validators.ALL_VARS` (validate first).
            Empty values are omitted.
        dark: Same shape, for the ``prefers-color-scheme: dark``
            override. Empty values omitted; an empty dict suppresses
            the dark block entirely.
        filename: Override the output filename.

    Returns:
        :class:`SaveResult` describing what was written.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    path = (target_dir / filename).resolve()

    light_clean = _clean(light or {})
    dark_clean = _clean(dark or {})

    parts: list[str] = [_HEADER]
    parts.append(_emit_root_block(light_clean, indent=""))
    if dark_clean:
        parts.append("\n")
        parts.append(_emit_dark_block(dark_clean))
    text = "".join(parts)
    if not text.endswith("\n"):
        text += "\n"
    path.write_text(text, encoding="utf-8")

    return SaveResult(
        target_path=path,
        light_count=len(light_clean),
        dark_count=len(dark_clean),
        bytes_written=len(text.encode("utf-8")),
    )


def load_theme(target_dir: Path, *, filename: str = THEME_FILE) -> dict[str, dict[str, str]]:
    """Round-trip an existing ``regstack-theme.css`` back into the
    designer's form state.

    Returns ``{"light": {...}, "dark": {...}}`` — both dicts are empty
    when the file doesn't exist, isn't readable, or doesn't match the
    expected ``:root { ... }`` shape (the designer just starts from
    defaults in that case).
    """
    path = target_dir / filename
    if not path.exists():
        return {"light": {}, "dark": {}}
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {"light": {}, "dark": {}}

    # Find the dark block FIRST so we can carve it out of the text
    # before searching for the light :root — otherwise the regex
    # would match :root inside the @media wrapper too.
    dark: dict[str, str] = {}
    dark_match = _DARK_BLOCK.search(text)
    if dark_match:
        dark = _parse_block(dark_match.group(1))
        text = text[: dark_match.start()] + text[dark_match.end() :]

    light: dict[str, str] = {}
    light_match = _LIGHT_BLOCK.search(text)
    if light_match:
        light = _parse_block(light_match.group(1))

    return {"light": light, "dark": dark}


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _clean(vars_: dict[str, str]) -> dict[str, str]:
    """Drop empty values and unknown keys; coerce bare-number radii to px."""
    out: dict[str, str] = {}
    for name, raw in vars_.items():
        if name not in ALL_VARS:
            continue
        if raw is None:
            continue
        value = raw.strip() if isinstance(raw, str) else str(raw).strip()
        if not value:
            continue
        if name in RADIUS_VARS and value.isdigit():
            value = f"{value}px"
        out[name] = value
    return out


def _emit_root_block(vars_: dict[str, str], *, indent: str = "") -> str:
    if not vars_:
        return f"{indent}:root {{ }}\n"
    lines = [f"{indent}:root {{"]
    for name in ALL_VARS:
        if name in vars_:
            lines.append(f"{indent}  {name}: {vars_[name]};")
    lines.append(f"{indent}}}")
    return "\n".join(lines) + "\n"


def _emit_dark_block(vars_: dict[str, str]) -> str:
    inner = _emit_root_block(vars_, indent="  ").rstrip("\n")
    return f"@media (prefers-color-scheme: dark) {{\n{inner}\n}}\n"


def _parse_block(body: str) -> dict[str, str]:
    return {m.group(1): m.group(2).strip() for m in _VAR_LINE.finditer(body)}


__all__ = [
    "THEME_FILE",
    "SaveResult",
    "load_theme",
    "save_theme",
]
