"""Build the real sdist and assert what's inside it.

``test_sdist_excludes.py`` checks the *exclude list* in pyproject.toml.
That's a denylist: it protects against exactly the paths someone thought
to name, and nothing else. It passed for months while the built tarball
shipped ``.claude/settings.local.json`` — the permission allowlist with
five absolute developer home paths — because ``.claude/`` was untracked
but not gitignored, and hatchling's sdist sweep includes files in that
state. The denylist can't fail for a path nobody predicted.

This module inverts the contract. It builds the actual tarball and
compares its top level against an *allowlist*, so anything new has to be
declared here on purpose, and separately scans every file for absolute
home paths. A future stray file at the repo root fails the build instead
of shipping.

Slower than the pyproject check (it shells out to a real build), so it
lives in its own module and is marked ``sdist_build``. Run the fast
checks alone with ``-m "not sdist_build"``.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tarfile
import tomllib
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[2]

# Everything permitted at the top level of the extracted sdist. Adding an
# entry here is a deliberate decision to publish it to every user who runs
# `pip download --no-binary`. PKG-INFO is generated by the build backend.
_ALLOWED_TOP_LEVEL = frozenset(
    {
        ".gitignore",
        "CHANGELOG.md",
        "LICENSE",
        "NOTICE",
        "PKG-INFO",
        "README.md",
        "SECURITY.md",
        "pyproject.toml",
        "regstack.toml.example",
        "src",
    }
)

# Absolute filesystem paths identifying the machine that built the tarball:
# `/Users/<name>` (macOS) and `/home/<name>` (Linux, including CI runners).
#
# The lookbehind is what keeps URLs out. A path segment inside a URL is
# preceded by a word character — `console.cloud.google.com/projectselector2`
# `/home/dashboard` in the OAuth wizard template is a real link, not a leak —
# whereas a genuine filesystem path starts at a boundary: string start,
# whitespace, a quote, or `=`. Matching on that boundary distinguishes the
# two without needing a per-file exemption, which would blind the check to
# any future real leak in the same file.
_HOME_PATH = re.compile(rb"(?<![\w.-])/(?:Users|home)/[A-Za-z0-9._-]+/")

# Files whose content legitimately mentions a home-shaped path. Empty by
# design — an entry here needs a reason in review.
_HOME_PATH_EXEMPT: frozenset[str] = frozenset()


@pytest.fixture(scope="module")
def built_sdist(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """Build the sdist into a scratch dir and return the tarball path."""
    if shutil.which("uv") is None:
        pytest.fail(
            "uv is not on PATH. This project builds exclusively with uv "
            "(see CLAUDE.md), so a missing uv is a broken environment, not "
            "a reason to skip a packaging-contract test."
        )
    out_dir = tmp_path_factory.mktemp("sdist")
    proc = subprocess.run(
        ["uv", "build", "--sdist", "--out-dir", str(out_dir)],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        pytest.fail(f"uv build --sdist failed:\n{proc.stdout}\n{proc.stderr}")
    tarballs = sorted(out_dir.glob("*.tar.gz"))
    assert len(tarballs) == 1, f"expected exactly one sdist, got {tarballs}"
    return tarballs[0]


def _members(tarball: Path) -> list[str]:
    with tarfile.open(tarball, "r:gz") as tf:
        return tf.getnames()


def _top_level(names: list[str]) -> set[str]:
    """Entries directly under the single ``regstack-<version>/`` root."""
    top: set[str] = set()
    for name in names:
        parts = Path(name).parts
        if len(parts) >= 2 and parts[1]:
            top.add(parts[1])
    return top


@pytest.mark.sdist_build
def test_sdist_top_level_matches_allowlist(built_sdist: Path) -> None:
    """Anything new at the top level must be declared, not merely not-denied.

    This is the check the exclude list structurally cannot make.
    """
    unexpected = _top_level(_members(built_sdist)) - _ALLOWED_TOP_LEVEL
    assert not unexpected, (
        f"sdist ships undeclared top-level entries: {sorted(unexpected)}. "
        "Either exclude them in [tool.hatch.build.targets.sdist] or, if "
        "publishing them is intended, add them to _ALLOWED_TOP_LEVEL."
    )


@pytest.mark.sdist_build
def test_sdist_contains_no_absolute_home_paths(built_sdist: Path) -> None:
    """No file in the tarball may leak a developer or CI home directory."""
    offenders: list[str] = []
    with tarfile.open(built_sdist, "r:gz") as tf:
        for member in tf.getmembers():
            if not member.isfile():
                continue
            rel = "/".join(Path(member.name).parts[1:])
            if rel in _HOME_PATH_EXEMPT:
                continue
            handle = tf.extractfile(member)
            if handle is None:
                continue
            found = _HOME_PATH.search(handle.read())
            if found:
                offenders.append(f"{rel}: {found.group().decode('utf-8', 'replace')}")
    assert not offenders, "sdist leaks absolute home paths:\n  " + "\n  ".join(offenders)


@pytest.mark.parametrize(
    ("text", "is_leak"),
    [
        (b"/Users/jdrumgoole/GIT/regstack/src", True),
        (b"/home/runner/work/regstack/regstack", True),
        (b'path = "/Users/joe/projects/x"', True),
        (b"built at /home/dev/checkout/ on", True),
        # URLs: the segment is preceded by a word character, so it isn't a
        # filesystem path. The wizard template really does link to the first.
        (b"https://console.cloud.google.com/projectselector2/home/dashboard", False),
        (b"https://example.com/home/user/profile", False),
        (b"see /home/dashboard for info", False),  # no trailing segment
    ],
)
def test_home_path_pattern_distinguishes_paths_from_urls(text: bytes, is_leak: bool) -> None:
    """Pin the leak/URL discrimination.

    Without this, a later "simplification" of the pattern either starts
    failing on the Google Console link in the OAuth wizard template, or —
    worse — stops matching real leaks and the check silently passes.
    """
    assert bool(_HOME_PATH.search(text)) is is_leak


@pytest.mark.sdist_build
def test_sdist_ships_the_package_itself(built_sdist: Path) -> None:
    """Guard the inverse failure: an over-eager exclude that ships nothing.

    An allowlist test passes trivially against an empty tarball, so assert
    the package source is actually present and the version matches
    pyproject.
    """
    names = _members(built_sdist)
    assert any(n.endswith("src/regstack/__init__.py") for n in names), (
        "sdist contains no package source"
    )
    with (_REPO_ROOT / "pyproject.toml").open("rb") as f:
        version = tomllib.load(f)["project"]["version"]
    assert built_sdist.name == f"regstack-{version}.tar.gz"
